theme: minima
title: Mikhail Shchegolkov
author: Mikhail Shchegolkov
description: A portfolio of my projects that I did for ERP solutions, pet projects, and projects at the universities where I studied.





