remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Portfolio
author: Mikhail Shchegolkov
description: A portfolio of my projects that I did for ERP solutions, pet projects, and projects at the universities where I studied.

